apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace: default
spec:
  selector:
    app: app3 # The selector matches the pods with the label 'app: my-app'
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 8080 # Port inside the container
      nodePort: 30002 # Static port on the nodes to access the service
  type: NodePort # Exposes the service on a static port on each node
